version: 2

jobs:
  build_test:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
            - yarn-cache-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          background: true
          paths:
            - ~/.cache/yarn

      - run:
          name: Build
          command: yarn lint

      - run:
          name: Build
          command: yarn build

      - run:
          name: Dependency audit
          command: yarn audit

workflows:
  version: 2
  pr:
    jobs:
      - build_test
