version: 2

jobs:
  build_test:
    docker:
      - image: circleci/node:9@sha256:ca409318be6d710101d513950be1abeb3d04b04f2eb40eaa04f9b5797288275c

    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
            - yarn-cache-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Build
          command: yarn build

      - run:
          name: Test
          command: yarn test

workflows:
  version: 2
  pr:
    jobs:
      - build_test
