version: 2

jobs:
  build_test:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      - run:
          name: Build
          command: yarn lint

      - run:
          name: Build
          command: yarn build

      - run:
          name: Dependency audit
          command: yarn audit

workflows:
  version: 2
  pr:
    jobs:
      - build_test
